### PR TITLE
Fix build with Qt 6.6.x (fixes #120)

### LINKED ISSUE #120: Build error on Arch Linux
Building from the latest AUR 3.0.6 package crashes with the following error:
```
[ 44%] Building CXX object src/CMakeFiles/DownZemAll.dir/core/mimedatabase.cpp.o
In file included from /home/papavlos/.cache/yay/downzemall/src/DownZemAll-3.0.6/src/core/mimedatabase.cpp:17:
/home/papavlos/.cache/yay/downzemall/src/DownZemAll-3.0.6/src/core/mimedatabase.h:35:35: error: ‘QUrl’ does not name a type
   35 |     static QPixmap fileIcon(const QUrl &url, int extend = default_icon_size);
      |                                   ^~~~
/home/papavlos/.cache/yay/downzemall/src/DownZemAll-3.0.6/src/core/mimedatabase.cpp:85:9: error: no declaration matches ‘QPixmap MimeDatabase::fileIcon(const QUrl&, int)’
   85 | QPixmap MimeDatabase::fileIcon(const QUrl &url, int extend)
      |         ^~~~~~~~~~~~
```
I run Plasma desktop environment and have already built some other Qt-based packages without issues. Is there a missing dependency?
**yochananmarqos** - the maintainer of the AUR packages - also confirms the same error and lets me open this upstream issue here.
See: [https://aur.archlinux.org/packages/downzemall](https://aur.archlinux.org/packages/downzemalll)

### PR DESCRIPTION
**Pull request by BSDKaffee**
FreeBSD is in the process of updating Qt to 6.6.0 and we are seeing the same build error as in #120.

FreeBSD bug: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=275068
Build log: https://pkg-status.freebsd.org/package22/data/132amd64-default-foo/2023-11-18_08h04m12s/logs/errors/downzemall-3.0.6_1.log

### CODE REVIEW

**Review by setvisible — APPROVED** [review]

**Comment by setvisible** [comment]
Thanks for your contribution! A mysterious forgotten include!
